### ISSUE TITLE
return UPD for damage frequency

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#123]

**Comment by HenryGeorgist** [comment]
I think I lack some context on this issue. Can you help me understand what it is that is needed here?

**Comment by rnugent3** [comment]
We return a paired data damage frequency for preview compute. We want to return uncertain paired data so that interaction with the model takes place as uncertain paired data only.  

Best,

R Nugent III

**Comment by HenryGeorgist** [comment]
ah - in our message or in the return on that function call in simulation?

**Comment by HenryGeorgist** [comment]
should it just be a deterministic uncertain paired data?

**Comment by rnugent3** [comment]
I forgot you would send the data in a message. That should work?

**Comment by HenryGeorgist** [comment]
i made a method that converts paired data to uncertain paired data, that way if someone wants it as paired data, they can use it that way, if someone wants it as uncertain paired data, it is easy to convert it on the fly.
