### ISSUE TITLE
clean up monotonicity checks

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#126]
use @HenryGeorgist 's rule stuff

**Comment by rnugent3** [comment]
william.lehman
11:31 AM
i think we do it in the sample method directly
so any time we produce a paired data from a sample of uncertain paired data
we call validate

richard.nugent
richard.nugent
11:32 AM
Ok. I'll write an issue to clean up the monotonicity check


william.lehman
11:32 AM
then we only have other cases where we dont interact with uncertain paired data itself
we also should have validation on uncertain paired data itself
that way when simulation calls validate we just validate all the curves too

**Comment by HenryGeorgist** [comment]
i found that we are producing non monotonic paired data all over the place

**Comment by HenryGeorgist** [comment]
```
        public IPairedData SamplePairedData(double probability)
        {
            double[] y = new double[_yvals.Length];
            for (int i = 0; i < _xvals.Length; i++)
            {
                y[i] = _yvals[i].InverseCDF(probability);
            }
            PairedData pd = new PairedData(_xvals, y, Category);//mutability leakage on xvals
            pd.Validate();
            if (pd.HasErrors){
                throw new Exception("the produced paired data is not monotonically increasing."); //TODO: be more intellegent abou this. possibly use force monotonic in range from go-consequences.paireddata
            }
            return pd;
        }

```

**Comment by HenryGeorgist** [comment]
this fails 12 of our tests. mostly levee tests i think. i can fix the issue i think for a temporary patch, but there is something wrong here.

**Comment by rnugent3** [comment]
The probability of failure is constant at and over top of levee elevation 

Best,

R Nugent III

**Comment by HenryGeorgist** [comment]
yeah - so errors are existing even if we have increasing values. there is still some serious problems going on that we need to probably fix, but i have it passing all tests.

**Comment by HenryGeorgist** [comment]
implemented strict monotonic increasing and monotonic increasing. need to finish decreasing - it is a bit trickier

**Comment by rnugent3** [comment]
Yes, I agree. Closing issue.
