### ISSUE TITLE
IsConverged = true where ConvergedIteration = 1. 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#132]
The .98 cnep histogram is converging on one iteration, and I think this results in the entire compute coming to a stop. This occurs in PerformanceTests.ComputeConditionalNonExceedanceProbability_Test() on the Feature/GraphicalInSimulation branch.

![image](https://user-images.githubusercontent.com/25163165/152611991-6d9a93c7-6933-48ab-8f94-ffb7007354b0.png)

**Comment by rnugent3** [comment]
looks like this issue is based in fda-statistics not fda-model. I used a hacky/temp fix that set minimum observations at 10000.

**Comment by HenryGeorgist** [comment]
just a sec

**Comment by HenryGeorgist** [comment]
statistics should be defaulting to min = 100

**Comment by HenryGeorgist** [comment]
i need to add validation on convergence criteria inside of the compute method to disallow min iterations = 0 if a random provider is being used instead of a mean random provider

**Comment by HenryGeorgist** [comment]
yep, just forgot to reference it in the commit log.
