### ISSUE TITLE
What is this backup project? Can we just delete this?

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/fda-model#140]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/475f00c7c5e375c72681cf426f7c4e68964a4a34/fda-model-test/fda-model-test%20-%20Backup.csproj#L2

**Comment by HenryGeorgist** [comment]
i think this was due to me using .net 6.0 for the performance testing stuff.

**Comment by rnugent3** [comment]
First time I am seeing this. I am good to delete.
