### ISSUE TITLE
log normal pdf and cdf look wrong.

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/fda-model#153]
neither the pdf or cdf are scaled by the log normal standard deviation nor mean..

**Comment by rnugent3** [comment]
From @HenryGeorgist:

- i think it just needs to be scaled - it is not quite right but it is close
- and we need to do Normal.StandardNormal(random) instead of constructing a Normal
- it is a static method on normal now
- it is faster than constructing and sampling
