### ISSUE TITLE
PairedData sorted independently could lead to 'unpairing'

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#185]
The SamplePairedData function in the UncertainPairedData class independently sorts X and Y values when either are non-monotonically increasing. This seems like it would essentially "unpair" the data, since after this sort operation any given x values index will no longer point to the same y value, unless both get sorted identically. The GraphicalUncertainPairedData class does the same sorting when sampled X and/or Y values are not monotonically increasing.

For an example, consisder an UncertainPairedData instance in which the distributions for increasing X values had increasing widths such that the low end of x would be lower than that of x-1. The GraphicalUncertainPairedData class appears to prevent this by forcing the standard deviation of all y values to be <= to that of the previous x value, but there doesn't seem to be any mechanism for doing this within the UncertainPairedData class. If this is the case, there could be probabilities for which a sampled curve will not be monotonically increasing, and when that curve is sampled, before being returned by the SamplePairedData function the Y values would be sorted. This would again untether them from the 'paired' X values. I tried to show this example in the image below. In this example the sampled/sorted curve no longer has any direct connection to the data it was generated from and is at that point basically arbitrary. 

![image](https://user-images.githubusercontent.com/7873755/155220024-61dafedb-f8c2-471c-b410-9971a13cc06c.png)

If my understanding of how this works is correct, it may be better to have distribution specific methods for enforcing the tails (or at least the lower bound) for a given X value are >= those for X-1. In any case I would say that X and Y values in paired data should probably not ever be sorted independently.

**Comment by rnugent3** [comment]
Good point. We have been working on this topic a lot. If I am not mistaken, @HenryGeorgist removed any notion of sorting from UncertainPairedData and from PairedData under fda-model >> paireddata.

I should remove the notion of sorting from GraphicalRelationships under statistics. 

Our approach assumes the following: 

1. Generally, monotonicity will be validated as the user enters data. The user will not be able to save a relationship that is not monotonically increasing **in the tails**.
2. Graphical frequency curves are the one situation where FDA will handle non-monotonicity in the tails because FDA computes the confidence limit about relationship. That said, stage/flow must be monotonically increasing with decreasing exceedance probability and this will be validated as the user enters data.   

Will removing any sorting in graphical relationships satisfy this comment?

**Comment by rnugent3** [comment]
ah - one thing - we will also have to handle non-monotonicity in the tails of damage distributions for internally computed aggregated stage-damage functions for the same reason as graphical frequency relationships - though the chance of this happening is much lower. for graphical it will happen often.

**Comment by HenryGeorgist** [comment]
In UncertainPairedData we have a method for checking extreme values for monotonicity. 
https://github.com/HydrologicEngineeringCenter/fda-model/blob/eef2d56957281368b224e212ec2e2fbe2cd0250b/fda-model/paireddata/UncertainPairedData.cs#L77

That should make the presence of the error very low (but still remotely possible). 
In the sample method of uncertain paired data there is still sorting of the X or Y values if there are errors on the sampled paired data object. 
https://github.com/HydrologicEngineeringCenter/fda-model/blob/eef2d56957281368b224e212ec2e2fbe2cd0250b/fda-model/paireddata/UncertainPairedData.cs#L128

I propose we eschew sorting in that situation (on the sample method of the uncertain paired data object) and move towards something like in go-consequences to "force monotonicity in range"
https://github.com/USACE/go-consequences/blob/0cf15f74f9ab95b1bf0c1c247a5b83c197b7b1cf/paireddata/paireddata.go#L46

That reduces the error associated with sorting and "unpairing the data" and more safely addresses the issue of sampling extremes infrequently through a more sanitary means.

**Comment by rnugent3** [comment]
I missed the sorting on sample paired data. So it sounds like two actions for resolution: (1) remove sorting for graphical relationships, and (2) force monotonicity in range for uncertain paired data. @AlexRyanUSACE what do you think?

**Comment by AlexRyanUSACE** [comment]
@rnugent3 that sounds good to me. For the forced monotonicity, I had been thinking in my original comment that could be handled in the UncertainPariedData by the constructor (maybe distribution type specific methods that would adjust the the Y value distributions such that a non-monotonically increasing curve could not be sampled), rather than adjusting an output curve on sample. @HenryGeorgist it looks like your "force monotonicity in range" function will basically replace any sampled value less than y(x-1) with y(x-1) so the effective distribution would be sort of truncated but with a spike at that end (number 2 in the crudely drawn image below).

![image](https://user-images.githubusercontent.com/7873755/155335292-e8a87823-5641-477d-a2e1-90c56dde1892.png)

It seems like is probably a better approach to do that (number 2) on creation of sample curve than to mess with the distributions, but i probably don't understand the statistics (or the possible ramifications) well enough either way. I guess it would come down to whether we're saying having Y value distributions that will return non-monotonically increasing curves sometimes is itself in error (in which case i'd advocate for number 1), or just that specific sampled y values that are not monotonically increasing are. Another thing to consider is that for the graphical relationships it looks like we are going the number 1 route, by adjusting the y value distributions in the constructor, but i don't know if we care about consistency between these two. Lastly, although this probably shouldn't be much of a consideration, i would expect number 1 to be more performant since you would be iterating only once through the paired data, instead of on every iteration.

**Comment by HenryGeorgist** [comment]
on the constructor of the uncertainpaired data we call addrules, add rules adds a rule to test monotonicity at the value .99 and .01 on all distributions in the y to verify that they would produce monotonically increasing curves within that range of values (for the implemented distributions). I can increase the probability range there to .999 or even further if we desire.
After construction, when a programmer calls validate, the rules are used to determine if the constructed object has "valid" data. all of our data is validated in the simulation, so we can be certain that these methods get executed and the tests you ask for do get called.

However, there is currently a less than (1-.99)*2 chance that a non monotonic curve might get sampled. in those cases we currently sort. i suggest we should truncate, which would have the artifact you describe at the extremes, but each curve would not be in the exact same location, so it wouldnt be a peak, it would be more like a shelf. Either way it is very small likelihood of occuring.

We can increase our testing range to .9999 and drop that by 2 orders of magnitude of occurrence.

**Comment by rnugent3** [comment]
Will has updated the sample method and implemented force monotonic. I have removed sorting from Graphical here: https://github.com/HydrologicEngineeringCenter/fda-model/pull/186/commits/8ce37451fa039943c80fb6cfc5353741df050cdb @AlexRyanUSACE could you please confirm if these actions satisfy your concern?

**Comment by AlexRyanUSACE** [comment]
> 

@rnugent3, yes this satisfies my concern, sorry for the late reply here!
