### ISSUE TITLE
Results class convergence testing not correctly testing across thresholds

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#189]
The IsPerformanceConverged function (line 21) iterates through the ThresholdsDictionary to pull CNEP convergence status from the values, but breaks and returns the results of the first entry in the dictionary. The same is effectively true for TestResultsForConvergence (CNEP convergence) and RemainingIterations (CNEP remaining iterations for the first threshold olny). If the intent is to return true (or expected iterations) when all thresholds are converged, it may be better to set a variable (isConverged  or something) to true, and then iterate through the dictionary setting it to false when any thresholds have not converged, or in the case of iteration count setting the return value equal to EAD iterations remaining, and then overwriting with any performance iteration counts that are > the current max. If the intent is to return convergence or iteration counts for a set threshold, the threshold key should be passed as a parameter to these functions.

**Comment by HenryGeorgist** [comment]
good catch. i think there needs to be a if (!converged) return false sort of statement inside the for each loop rather than an if isconverged return isconverged.

**Comment by AlexRyanUSACE** [comment]
I haven't been able to test it unfortunately, i just got the 4.8 .net framework installed yesterday, so to date i've just been sort of reading through the code. I do have it now though and so can build and execute, and this morning put together a very simple test program thingy, so i can create one if we want to do that.

**Comment by HenryGeorgist** [comment]
there should already be a test program thingy

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/main/fda-model-cmd/Program.cs

or all of the unit tests.

**Comment by rnugent3** [comment]
@AlexRyanUSACE - not testing but just reading the code? REALLY good catch. Writing unit tests is on me. @HenryGeorgist I look forward to your feedback on the PR.

**Comment by rnugent3** [comment]
@AlexRyanUSACE please take a look at this PR: https://github.com/HydrologicEngineeringCenter/fda-model/pull/192

I have updated the logic and added a test confirming that the logic fits the bill.
