### ISSUE TITLE
The ForceDeQueue method in the ThreadsafeInLineHistogram class can result in deadlock

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#197]
The ForceDeQueue method in the ThreadsafeInLineHistogram class can result in deadlock, with the background thread (potentially?) waiting on itself forever. Will already found the solution when we were talking earlier today; adding "if (_observations.Count > 0) break;" to the line after the Thread.Sleep, so this is really just a note to remind him or someone to make the change. Also it would probably be better to change Thread.Sleep(1) to something ~ 200 - 1000.

**Comment by HenryGeorgist** [comment]
i think the threadsleep should be short, maybe we do 1 until coerced again

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/6fb7e5626c2bdec588b1897252b0f278c63b4818/Statistics/Histograms/ThreadsafeInlineHistogram.cs#L287

this is the reference line - add the solution in the op to the line below thread.sleep
