### ISSUE TITLE
The InterpolateQuantiles class does not reproduce previous FDA version graphical curve interpolation

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#202]
The Interpolate Quantiles class does not accurately reproduce interpolated discharge probability curves from a series of ordinates as done in previous versions of FDA. I can't actually tell (and the manual doesn't appear to state) the interpolation method used in eg FDA 1.4.2, but it looks somewhat similar to the results of a cubic spline interpolation. In the test study used for this comparison, the following series of ordiantes were used:

0.999	80
0.5	11320
0.2	18520
0.1	23810
0.02	35010
0.01	39350
0.005	42850
0.001	47300

For the area of the curve 0.0001 – 0.5, the quantile method used in FDA 2.0 very closely mirrors the curve generated in FDA 1.4.2 using the same ordinates, however the two curves diverge dramatically in the range of 0.5 – 0.999, as shown below. In the test study, the FDA 2.0 simulation resulted in mean EAD over 10x higher than in the FDA 1.4.2 model.

![2022_04_11_17_08_35_Document3_Word](https://user-images.githubusercontent.com/7873755/162833254-45ffe983-e99d-4066-86a9-8bf49f77b683.png)

It’s hard to say what the solution here should be (or even really what the problem is?) without knowing how previous versions of FDA performed this interpolation, but my general impression is that the FDA 2.0 interpolation seems incorrect given the degree to which the interpolated points bulge outward, shown better below:

![2022_04_11_17_09_03_Document3_Word](https://user-images.githubusercontent.com/7873755/162833371-60b4963f-ab23-49d7-9715-f64b9870b0ab.png)

The following workbook attempts to replicate the ComputeQuantiles method in the InterpolateQuantiles class for testing:

[Quantile Interpolation Test.xlsx](https://github.com/HydrologicEngineeringCenter/fda-model/files/8467769/Quantile.Interpolation.Test.xlsx)

**Comment by HenryGeorgist** [comment]
interesting. I dont know if this is good or bad, but it is great that you identified this and gave this evidence!

**Comment by AlexRyanUSACE** [comment]
Okay, i figured it out. Beth was right in here email, the interpolation for discharge frequency should be log, not linear. This should have been obvious to me after i plotted, given how it's bunched up. So right now the code is using standard normal distribution approach to compute a percentage along the quantile and then multiplying that by the difference between x1 and x2, when it should be using the log interpolation formula instead; x = x2^f * x1^(1-f). I've attached the workbook where i tested this and was able to duplicate the FDA curve exactly.

So i think the code should be as follows (roughly obviously):

the line that currently reads
output[i] = _InputXValues[inputOrdinate - 1] + ((xk - xk1) / (xk2 - xk1)) * (_InputXValues[inputOrdinate] - _InputXValues[inputOrdinate - 1]);

should instead be 
double pctval = ((xk - xk1) / (xk2 - xk1)); //i added this line to make the next easier to read
output[i] = Math.Pow(_InputXValues[inputOrdinate], pctval) * Math.Pow(_InputXValues[inputOrdinate - 1], 1 - pctval);


[New graphical interp test.xlsx](https://github.com/HydrologicEngineeringCenter/fda-model/files/8475342/New.graphical.interp.test.xlsx)

**Comment by rnugent3** [comment]
Thanks, Alex! Working on this now.

**Comment by rnugent3** [comment]
2.0 results are closer using a logged data and log-linearized interpolation than using unlogged data with log interpolation. Seems strange. Also strange that the Alex's work in Excel matches 1.4.3 results closer than 2.0 results.
