### ISSUE TITLE
GraphicalUncertainPairedData still uses independent X value sorting to address monotonicity errors

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#208]
On line [151](https://github.com/HydrologicEngineeringCenter/fda-model/blob/9bf5f2159a03ef3ae9e6f4ca78d1223f9787cf96/fda-model/paireddata/GraphicalUncertainPairedData.cs#L153) of the GraphicalUncertainPairedData class, the SamplePairedData method will still sort values if monotonicity issues are detected on X values. As stated in a previous comment, i don't think paired data x or y vals should ever be sorted independently, in particular not to resolve monotonicity issues. Here I think it would be fine to probably just throw an error message, as the X values are fixed (not sampled) and should have already been subjected to at least one monotonicity test at this point. If this issue ever came up (which it shouldn't anymore if issue #204 and related are addressed) something pretty bad would have had to have happened, so rather than to attempt an automated fix it would probably be best to just throw an error.

**Comment by rnugent3** [comment]
what about changing the forcemonotonic method to handle both x and y, do away with sorting entirely?

**Comment by rnugent3** [comment]
you're right, the x values have already been validated for monotonicity.

**Comment by rnugent3** [comment]
there is no more sorting anywhere
