### ISSUE TITLE
Enum for stage-damage funtions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#215]
We are going to have a stage-damage function for a damage category - damaged item category. 

The damage categories are typically residential, commercial, industrial, and public. Other damage categories like emergency/clean-up costs and agriculture are less common but still relevant. The damaged items include structure, content, and other. 

Do we want to develop something like a string enum with all the combinations to track all of the stage-damage functions?

_Originally posted by @rnugent3 in https://github.com/HydrologicEngineeringCenter/fda-model/discussions/102_

**Comment by rnugent3** [comment]
A stage-damage enum means that we're going to hard-code damage categories (residential, commercial, industrial, public....) and asset type (structure, content, and other). This seems like unnecessary rigidity. I feel like our current approach is the most flexible. 

Could we use a combination of damage category and asset type for the string argument of the (stage-damage) uncertain paired data object? Something like "structure-residential" and "content-residential." I think this could be easily coded using string interpolation. This would fit right into the current computational code. The only downside I see is parsing the strings to display the correct results, but parsing strings shouldn't be too problematic, right?

Alternatively, we could add an additional string argument to the constructor for the asset type. The downside there is that we'd have another dimension over which to iterate. 

@Brennan1994 @HenryGeorgist @codymccoy I'd appreciate your input. Thank you!

**Comment by rnugent3** [comment]
@codymccoy suggested extending UPD

**Comment by rnugent3** [comment]
BE aware of the 19 references that use the constructor of the UPD with category

**Comment by rnugent3** [comment]
@HenryGeorgist suggests doing an enum in the curve metadata and adding a method "Type" to return the enum to the upd and pd interfaces

**Comment by HenryGeorgist** [comment]
honestly, a string (the category string) in the metadata is my preferred way of doing this.

if this is not sufficent we can add an enum to control the options.

**Comment by rnugent3** [comment]
I think the issue is that we have two different sets of categories: damage categories and asset categories. combining these things into a joint string category seems like it could make using this code kind of messy. How do you handle it in go-consequences?

**Comment by rnugent3** [comment]
I've done some work using an enum for damage category. What do we think this means for the code that uses this code? For example, when a user imports occupancy types, do we try to match, and if we can't, leave the damage category unassigned and warn the user that some damage categories have not been assigned?

**Comment by rnugent3** [comment]
we might match with 4 different variations of the damage category, e.g. for residential:

- "res"
- "RES"
- "residential"
- "RESIDENTIAL"
