### ISSUE TITLE
damage frequency string message not working

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#229]
![image](https://user-images.githubusercontent.com/25163165/169406977-433a041b-7a60-4559-858d-b174bc191fc0.png)

**Comment by rnugent3** [comment]
@codymccoy is this still an issue? I've lost track.

**Comment by codymccoy** [comment]
Or we just leave it and back away slowly.

**Comment by rnugent3** [comment]
@codymccoy why are lines 519 - 521 required? It seems like if line 516 is true then it must be that line 519 is true, though I could absolutely be missing something. In any case, I've changed the string to "FrequencyDamage"
