### ISSUE TITLE
metrics.AlternativeComparisonReportResults.GetDamageCategories() NPE

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/fda-model#261]
I am getting a null pointer when trying to get the damage categories from metrics.AlternativeComparisonReportResults

![image](https://user-images.githubusercontent.com/47757848/174158334-48ca20ab-2b5f-41a2-9ee1-6da099b6990f.png)

**Comment by rnugent3** [comment]
My unit test is passing. See: 

https://github.com/HydrologicEngineeringCenter/fda-model/blob/86473d2573afd964e3a288cab0a1cdf0450379d7/fda-model-test/unittests/AlternativeComparisonReportTests.cs#L186

Closing this issue.
