### ISSUE TITLE
Scenario Results: Assurance of threshold

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/fda-model#263]
All of my results are NaN:
![image](https://user-images.githubusercontent.com/47757848/174100249-be677498-b92d-42e2-8760-39c43d6dc170.png)

This is the call to get the values:
![image](https://user-images.githubusercontent.com/47757848/174101314-0ceb3686-93eb-4e95-bc79-526f4f7cdf71.png)

In this case i don't have any extra thresholds, only the default. The threshold key is zero.

**Comment by rnugent3** [comment]
I have written tests to show that we're getting results for several study configurations using the default data. However, there are probably weird cases I've not covered that should be tested. E.g. what if the rating curve ends before the 1% event? The range of stages for which damage is calculated is identified by the lower confidence limit of the lowest stage distribution to the higher confidence limit of the highest stage distribution. I believe that the stage is held constant beyond the highest defined coordinate. We **should** still get a result, though it wouldn't make much sense.

**Comment by codymccoy** [comment]
@rnugent3 I am still getting NaN, but i am using different numbers than you show above. 

![image](https://user-images.githubusercontent.com/47757848/175992620-77c06bec-edf2-42b8-a97d-d2b7720a9303.png)

Am I supposed to use .9, .96, .98, .99, .996, .998 values AND display those values in the table or do I just use those values to get the assurance value but leave the table alone?

**Comment by codymccoy** [comment]
I switched to these values and now have all zeroes.

![image](https://user-images.githubusercontent.com/47757848/175993417-a74dc90b-69c5-410c-90e6-4cf2c73966b2.png)
