### ISSUE TITLE
AssurancyOfAEP is throwing an exception

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/fda-model#268]
I am getting the following exception when trying to create the results for the scenario:
![image](https://user-images.githubusercontent.com/47757848/173837735-9f66fbde-d7f5-46a9-bbad-d3df7f1e11b3.png)

This is where i call that line:
![image](https://user-images.githubusercontent.com/47757848/173837899-10288b11-8402-43b9-b291-cb934a428d76.png)

**Comment by rnugent3** [comment]
My unit test with non-overlapping stages (stage discharge with stages both entirely above and entirely below stages of stage damage) passes with expected assurance of AEP (0 and 1, respectively)
