### ISSUE TITLE
FDA Log File Better Messaging

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/fda-model#270]
The compute appears to produce millions of lines of "EADMessage". This should be improved.

![image](https://user-images.githubusercontent.com/47757848/173442144-519a593d-47ed-4771-94b7-4a808cfd7cea.png)

This log file gets written next to the sqlite file:
![image](https://user-images.githubusercontent.com/47757848/173442233-c9d769ab-2803-4482-824c-e8a80222dfe2.png)

**Comment by rnugent3** [comment]
With the already existing ReportProgress messaging that is called after each progress chunk and the ComputeCompleteMessage - that should be enough for the compute log, so it seems that we just need to make sure that we have the subscriptions set up. 

Except for the errors we've handled, is there anything else we'd want to communicate as the compute occurs?

**Comment by rnugent3** [comment]
I think we'd want to add the following messages:

1. Simulation initiated, we're checking for errors
2. Then messages come out of CanCompute(). If can compute returns true, a message confirming that we can compute. 

Then optionally we could provide statistics with the progress report.

**Comment by rnugent3** [comment]
At the below line, do we want to call GetErrors()  ? I suppose that would then have to be passed through a message?

https://github.com/HydrologicEngineeringCenter/fda-model/blob/bc3fae7e7dd515ce7680c758bd704088912ef2bb/fda-model/compute/ImpactAreaScenarioSimulation.cs#L127

**Comment by rnugent3** [comment]
I think what we have will have to cut it for now - messaging is complicated and we have lower hanging fruit. Let's put this in backlog.
