### ISSUE TITLE
return list of impact areas 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#273]
double check that all dimensions can be listed

**Comment by rnugent3** [comment]
@codymccoy we've been tracking the ID of a given impact area only. Does a list of the IDs of the impact areas meet your needs, or shall I refactor to return a List<ImpactArea> 

We've not made use of the ImpactArea object. It seems thus far it has not been necessary, though this may be the use case requiring that we do use the ImpactArea object.

**Comment by codymccoy** [comment]
This is what I am currently doing:
![image](https://user-images.githubusercontent.com/47757848/174847618-882fb482-155a-4bba-b238-8c9edfb1bca7.png)

And then i grab our impact areas and match to the id's:
![image](https://user-images.githubusercontent.com/47757848/174847685-812412ff-747e-4ffd-99bb-986fb6e905e7.png)

**Comment by codymccoy** [comment]
I am not sure how to get the id's with an AlternativeResults object:
![image](https://user-images.githubusercontent.com/47757848/174847945-29694eb1-76e4-4ef2-ad90-dcf4614648b7.png)

**Comment by codymccoy** [comment]
If we go with what i am currently doing, then we just won't display a row if the impact area doesn't exist anymore. If you had an internal list of the string names of the impact areas, then this wouldn't depend on the impact areas still existing in fda. It sounds like that might be tough to do. I am fine with the way it is currently working. I could maybe add a popup message telling the user that an impact area doesn't exist anymore that we have results for.

**Comment by rnugent3** [comment]
> If we go with what i am currently doing, then we just won't display a row if the impact area doesn't exist anymore. If you had an internal list of the string names of the impact areas, then this wouldn't depend on the impact areas still existing in fda. It sounds like that might be tough to do. I am fine with the way it is currently working. I could maybe add a popup message telling the user that an impact area doesn't exist anymore that we have results for.

@codymccoy  What would it take to delete an impact area? We're not modifying the shapefile at all with the UI, right? So the user would have to delete the impact area set and reimport a new one without the given impact area. It seems if that is the case - then the user is undertaking effort to remove the impact area, and so I think it would then be natural to not display results for the deleted impact area.

**Comment by codymccoy** [comment]
You are correct. If the user deletes the impact area set, I believe we pop up a message that lists the scenarios that rely on those impact areas, and we delete those also if the user wants to continue with the delete.
