### ISSUE TITLE
histogram parameter optimization

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#282]
I wonder if there is a way to optimize histogram parameters (min, binwidth) as the histogram grows. I think that setting these things ad hoc is leading to some weird histograms.

**Comment by HenryGeorgist** [comment]
you absolutely can. especially if you store your data elements.  the objective of inline histogram is to convert millions of single or double precision values into a thousand int64 or int32's on the fly.  This gives the ability to have an infinate stream of homogeneous data pointed at an object to stream data into.

To do that i discard the data as it is being generated - the sacrifice is flexibility in binning.

Once you make a bin in inline histogram you cannot subdivide the bin without possibly making a mistake, however, you can sum adjacent bins without making a significant mistake.

So you can go from 1000 bins down to 500 or something like that. 

An option is to make a new histogram type that operates off of a complete set of data.  This is the more traditional usage of histograms, and i think is a completely valid and relevant tool to have in the toolbox.

**Comment by rnugent3** [comment]
To test for convergence, would we toss the list of obs into a histogram, test if converged, and drop the histogram and keep adding obs to the list if not converged?

**Comment by HenryGeorgist** [comment]
The class would store all observations and you could write convergence however you want on that array. If you make a histogram test for convergence and then discard it that could work.

where are the weird histograms happening? In ead or elsewhere?

you can also increase min iterations. The larger the min iterations the better the initial guess of binning will be. We apply sturges rule when min iterations is exceeded.

**Comment by rnugent3** [comment]
The weird histograms are largely the various damage histograms. the performance histograms come out okay. 

Moving from collecting observations in a histogram to collecting observations in a list, we'd want to collect observations in a thread-safe collection? see https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/

**Comment by HenryGeorgist** [comment]
or simply an array - in the compute loop we have seeds for each iteration up to max iterations, and each compute in the paralell for loop has an index, so you would set the damage at that index in the array.

**Comment by rnugent3** [comment]
@HenryGeorgist I am going to work on this today. A couple questions for you:

1. Do I understand correctly that I can add damage observations to a double[] at the index of the iteration in a parallel compute?
2. What is the benefit to having a class that holds the observations as opposed to holding the observations within the simulation class and passing into the histogram when it is time to check for convergence?

**Comment by rnugent3** [comment]
One more - if we are adding observations to a double[], we won't need a threadsafe histogram for the compute?

**Comment by HenryGeorgist** [comment]
1. yes.
2. it depends on what you are doing.

1 million doubles is alot of memory - i generally advise against this. How are you instantiating the inline histograms for damages, are you starting them with a min and a max value?

**Comment by rnugent3** [comment]
this is the constructor I put together: 

```         public Histogram(double[] data, ConvergenceCriteria convergenceCriteria)
        {
            _ConvergenceCriteria = convergenceCriteria;
            Min = data.Min();
            Max = data.Max();
            int quantityOfBins = (int)Math.Ceiling(1 + 3.322 * Math.Log10(data.Length));
            double range = Max - Min;
             _BinWidth = range / quantityOfBins;
            AddObservationsToHistogram(data);
        }

**Comment by HenryGeorgist** [comment]
how big is data?

**Comment by rnugent3** [comment]
with the approach I have in my head, data can be as big as max iterations

**Comment by HenryGeorgist** [comment]
I was generally thinking differently, if you know an impact area damage function, you can pull the max and min of it - and have a number of bins you want to include, and set it directly (no struges)

**Comment by HenryGeorgist** [comment]
simulation.impactarea.damagecategory.assettype. min and .max general idea...

**Comment by rnugent3** [comment]
how do you see the max of the value of damage that has a .0001 chance of being exceeded translating to the max of EAD?

**Comment by rnugent3** [comment]
I would like to avoid setting the number of bins ad hoc

**Comment by rnugent3** [comment]
because the number of bins optimally depends on the number of observations which depends on convergence

**Comment by rnugent3** [comment]
though, concurrent queue might not be a great measure. we've seen true convergence (according to our default criteria but very large max) happening in the millions, in which case the concurrent queue (min iterations) of 50k would not be all that great. 

we could use the same logic of estimate iterations remaining to get an ad hoc estimate.

**Comment by rnugent3** [comment]
currently happening here: https://github.com/HydrologicEngineeringCenter/fda-model/blob/86473d2573afd964e3a288cab0a1cdf0450379d7/Statistics/Histograms/ThreadsafeInlineHistogram.cs#L393

**Comment by rnugent3** [comment]
I think we can close this issue. For impact area scenario results, concurrent queue identifies the observation quantity for use with Sturges rule. If I recall correctly, the concurrent queue is set equal to the min iterations, though I was not able to verify through a quick review. For alternative and alternative comparison reports, we construct histograms on the fly after a set number of iterations to test for convergence, which means that the total number of observations in the histogram is the quantity used with Sturges rule.
