### ISSUE TITLE
2.0 flow uncertainty does not match 1.4.3 flow uncertainty 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#283]
The uncertainty in the right tails appear not to match between the two versions. In an investigation into pretty big differences in system performance metrics outcomes, I found that the flows in 2.0 tend to be lower than the flows in 1.4.3. Sometimes the difference is negligible, sometimes it is pretty large (up to 20% less). The difference appears to increase over the probability domain - particularly reaching into the right tail. I wrote these messages as part of the investigation: 

 The error between the 0.05th percentile of the histogram of 90th percentile flows as compared to the set of expected 90th percentile flows is -0.0250098617035856
The error between the 0.25th percentile of the histogram of 90th percentile flows as compared to the set of expected 90th percentile flows is -0.0162908159542671
The error between the 0.75th percentile of the histogram of 90th percentile flows as compared to the set of expected 90th percentile flows is -0.0211938077334564
The error between the 0.95th percentile of the histogram of 90th percentile flows as compared to the set of expected 90th percentile flows is -0.0463600880387826
The error between the 0.05th percentile of the histogram of 95th percentile flows as compared to the set of expected 95th percentile flows is -0.0440636340892282
The error between the 0.25th percentile of the histogram of 95th percentile flows as compared to the set of expected 95th percentile flows is -0.0236529010291206
The error between the 0.75th percentile of the histogram of 95th percentile flows as compared to the set of expected 95th percentile flows is -0.0206895216544568
The error between the 0.95th percentile of the histogram of 95th percentile flows as compared to the set of expected 95th percentile flows is -0.0412269597001525
The error between the 0.05th percentile of the histogram of 98th percentile flows as compared to the set of expected 98th percentile flows is -0.0806534801088074
The error between the 0.25th percentile of the histogram of 98th percentile flows as compared to the set of expected 98th percentile flows is -0.0375898539884481
The error between the 0.75th percentile of the histogram of 98th percentile flows as compared to the set of expected 98th percentile flows is -0.00922750353020602
The error between the 0.95th percentile of the histogram of 98th percentile flows as compared to the set of expected 98th percentile flows is -0.0139054696390122
The error between the 0.05th percentile of the histogram of 99th percentile flows as compared to the set of expected 99th percentile flows is -0.110350954315477
The error between the 0.25th percentile of the histogram of 99th percentile flows as compared to the set of expected 99th percentile flows is -0.0454819541148502
The error between the 0.75th percentile of the histogram of 99th percentile flows as compared to the set of expected 99th percentile flows is 0.00596859846616356
The error between the 0.95th percentile of the histogram of 99th percentile flows as compared to the set of expected 99th percentile flows is 0.0250115961186186
The error between the 0.05th percentile of the histogram of 995th percentile flows as compared to the set of expected 995th percentile flows is -0.134896920264278
The error between the 0.25th percentile of the histogram of 995th percentile flows as compared to the set of expected 995th percentile flows is -0.0458805118115807
The error between the 0.75th percentile of the histogram of 995th percentile flows as compared to the set of expected 995th percentile flows is 0.0474833219850161
The error between the 0.95th percentile of the histogram of 995th percentile flows as compared to the set of expected 995th percentile flows is 0.101617967488044
The error between the 0.05th percentile of the histogram of 998th percentile flows as compared to the set of expected 998th percentile flows is -0.207803777251567
The error between the 0.25th percentile of the histogram of 998th percentile flows as compared to the set of expected 998th percentile flows is -0.114173805740394
The error between the 0.75th percentile of the histogram of 998th percentile flows as compared to the set of expected 998th percentile flows is -0.0137761858700977
The error between the 0.95th percentile of the histogram of 998th percentile flows as compared to the set of expected 998th percentile flows is 0.0483452880301082

**Comment by rnugent3** [comment]
I am not sure what to make of this, other than it explaining the result that CNEP is higher in 2.0 than in 1.4.3.

**Comment by rnugent3** [comment]
I think we'll need a way to defend why our approach is better

**Comment by rnugent3** [comment]
the test I mentioned above is here: https://github.com/HydrologicEngineeringCenter/fda-model/blob/8cc3f2c7e402f020a0ba905d6e8ec28105925309/fda-model-test/unittests/simulationShould.cs#L270

**Comment by rnugent3** [comment]
I wonder whether this is a known difference between 17B and 17C? I understand that parametric bootstrap is _not_ 17C but closer to it, right?

**Comment by HenryGeorgist** [comment]
it is not 17C with ema but it is closer. It could also be the wilson hilferty transform, it is only robust in a certain range of means, standard deviations and skews. what is the parameterization of the lp3?

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/597a1a24bbc7a778a6e0b186d477bcd8a4b0528f/Statistics/Distributions/LogPearson3.cs#L166

we can check for skew and stdev ranges and switch to a more complicated and slower lp3 implementation if it is necessary.

**Comment by rnugent3** [comment]
```      LogPearson3 logPearson3 = new LogPearson3(3.3, .254, -.1021, 48); //dist in default data

**Comment by rnugent3** [comment]
@HenryGeorgist do you have the source of the robustness evaluation handy? I can carry out some more sensitivity analysis. 

I am not eager to swap implementations. The first thing I'd like to be able to do is show why our implementation is better.

**Comment by rnugent3** [comment]
We've shown for a few different data sets that the means are relatively well replicated, so this would only affect the system performance metrics and the distribution of damage

**Comment by HenryGeorgist** [comment]
wilson hilferty should work for skews up to around 3, so that is likely not the problem it is probably bootstrap instead of the non central t

**Comment by rnugent3** [comment]
We don't expect the two to match, so this is a non-issue.
