### ISSUE TITLE
exception when passing zero damage stage damage functions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#290]
When we pass in stages for a flow-frequency function, we hit an exception in ThreadsafeInlineHistogram EstimateIterationsRemaining

![image](https://user-images.githubusercontent.com/25163165/176046674-24ae5092-fc54-437e-ab78-2eb694dc44ac.png)

This is not an immediate priority - but we should spend time identifying the actual cause of this issue so that we can set up validation for it. I think it has something to do with logging the data - that is the only difference in how we handle stage vs flow. The difference in log stages will be really really tiny.

**Comment by rnugent3** [comment]
Could you please help me with what uxp and lxp and the other local variables represent?

**Comment by HenryGeorgist** [comment]
upper quantile x probability
lower quantile x probability
upper quantile f of x probability
lower quantile f of x probability

i generally derive those guesses from the values that the functions actually being referenced. InvCdf and PDF would yeild values that would be interpreted as such.

**Comment by rnugent3** [comment]
it turns out this is not just for bad data. This is happening with data from a real study (River Des Peres).

**Comment by rnugent3** [comment]
I think this has to do with overlap issues which could be handled through validation. writing a test to confirm.

**Comment by rnugent3** [comment]
this is happening when there are zero damages in the stage damage function

**Comment by rnugent3** [comment]
this issue has been fixed but might cause other issues. We will not compute if a stage-damage function has zero damage. If a user does not have stage-damage functions for all damage categories, will we run into a problem? this fix also escalates the priority of issue #248 where a workaround might have been a zero damage stage damage function but that will not work now.

**Comment by rnugent3** [comment]
I think we need to leave this issue open. It is possible there are other scenarios that lead to the exception. I think the overlap problem is one of those scenarios.

**Comment by rnugent3** [comment]
This issue is WEIRD. The test that I wrote to catch this issue and the fix I made are both working like I expect. When a stage damage function is passed into simulation builder and we call validate, the error level becomes severe, and a compute will not proceed. 

I can't tell that this is happening when a stage damage function with zero damage is being passed in from the UI. Even weirder, it seems that a damage function could be getting zeroed out? The damage function causing this issue has positive damage in the UI. When I look at the function in locals, it has zero damage. I'm looking at the Des Peres data set, impact area named "3" with impact area ID 1, dam cat Auto. This makes me think that the damage function is getting manipulated after validation but before compute. That would make the validation problem make sense, but how it would get manipulated does not make sense. 

I don't know. Something is happening where the validation does not catch the data, or the data changes after validation. 

I broke out the add property tule line into its many constituent parts living on separate lines to verify that the validation works when using the UI, but my breakpoints stopped getting hit, don't know why. 

@codymccoy unfortunately I won't be able to continue troubleshooting this weekend. I'm out of town and forgot my charger at home. I hope to be able to work on this Monday night.

**Comment by codymccoy** [comment]
One issue is that the impact area id's do not match with the impact area names. Here is the connection:

![image](https://user-images.githubusercontent.com/47757848/177224471-b266f49d-df93-4bf6-84e6-46ac19761eea.png)

I think there was some confusion over "1". If the UI is displaying "1" then that is the impact area name. If you are debugging and seeing impact area id of 1, then that matches to impact area with name "18". 

There is an exception when there are stage damages with y values that are all zero. I wrote a method just before computing that loops over all 100 of my damage curves and removes any with all zeros. This resulted in 37 curves being removed. The compute completed successfully.

**Comment by codymccoy** [comment]
There is a property rule on line 867 of ImpactAreaScenarioSimulatiom.cs

![image](https://user-images.githubusercontent.com/47757848/177224720-373ba109-7d17-4286-a108-9c95e257a7c9.png)

In the case i was looking at, there was a property name of "Auto stage damages". I don't see how that can ever get evaluated because that is not a valid property name.

**Comment by HenryGeorgist** [comment]
Validate evaluates all rules in the rule map. Regardless of ne.  Naming by property is good practice for vm development to take advantage of the validation native in binding, however it is not necessary for validation of objects in the model.  The validate method gets called on build and all validation rules get evaluated prior to computation.
