### ISSUE TITLE
Index out of bounds exception when getting results

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/fda-model#294]
This exception occurs when trying to view results on the "Low Flow" scenario in the cache creek study.
![image](https://user-images.githubusercontent.com/47757848/176471724-867c18f4-d8dd-467a-bbed-76f8773fe230.png)

The exception occurs here:
![image](https://user-images.githubusercontent.com/47757848/176471812-626c8413-c883-438f-9655-75896cb359b8.png)

**Comment by rnugent3** [comment]
@codymccoy this is not the only situation where you've hit this exception, right? we just hit this exception this morning going through the des peres study data. would you mind sharing with me what data was used when we hit that exception?

**Comment by rnugent3** [comment]
I see in the low flow that the frequency curve has an ERL of 0 which I expect to throw things off. We should probably have validation that the ERL should at least be 2.

**Comment by codymccoy** [comment]
I ran into this issue on this line:

![image](https://user-images.githubusercontent.com/47757848/177391755-1d8c9684-2d5f-4b14-b0b4-3e759d827504.png)

I was trying to view the scenario results on the "without base year" scenario.

**Comment by rnugent3** [comment]
this is happening because we are asking for the bin count of a value that is much larger than all values in the histogram
