### ISSUE TITLE
Exception when computing Alt Comp Report

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/fda-model#303]
When computing the alt comp report for the Peres study I ran into the following exception:

![image](https://user-images.githubusercontent.com/47757848/177414026-5a730568-924d-476b-b0df-f508a02cf3c6.png)

The issue is that the observation number is NaN.

From the documentation:
![image](https://user-images.githubusercontent.com/47757848/177414116-c3df7e41-595a-426b-961e-454f9e619bba.png)

**Comment by rnugent3** [comment]
I think there is an existing issue on this. I’m trying to fix it now. Let’s hope I have hair left once I do.

**Comment by rnugent3** [comment]
woops this is the existing issue!

**Comment by rnugent3** [comment]
the work on this issue has started with the alternative compute, next follows alternative comparison report, where we are producing results for dam cat - asset cat - impact area combinations that have a histogram of zero damage
