### ISSUE TITLE
overlap threshold

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#311]
make the overlap threshold less strict. if we're not computing results from data that came from 1.4.3, seems like we're not doing the job.

**Comment by rnugent3** [comment]
we hit the twos complement with a minimum threshold of 20% overlap. I have changed it back to 50%. We need to refine this in a way such that we're not saying "we can't compute risk for your study" for study data that came out of 1.4.3 in which the compute exited successfully. It probably means an overlap threshold in the middle and additional validation to handle lower levels of overlap.

**Comment by HenryGeorgist** [comment]
twos complement should not be solved by changing overlaps
it should be saved by appropriately handling the math in threadsafeinline histogram. enumerate the reasons why it happens .e.g (remaining iterations hits max int, consistant nan returns being provided for all iterations, 0 values for all iterations etc.) find all of those and then we need to handle the cases in inline histogram, not try to fix the inputs.

**Comment by rnugent3** [comment]
Well that is what I meant by additional validation. I have enumerated the reasons why it happens over the many commits and PRs over the last couple weeks. The problem is that I keep finding new ways that it happens after I've validated for those other reasons. 

For example, 0 values for all iterations is often the result of too little overlap. I don't fix the inputs when there is too little overlap, I abort the compute. Too little overlap has been handled by the overlap check.

**Comment by rnugent3** [comment]
I should make it very clear, we are not changing overlaps at all, that logic does not exist in the code nor is it planned. I am talking about refining the overlap _threshold_.

**Comment by rnugent3** [comment]
see: 

https://github.com/HydrologicEngineeringCenter/fda-model/blob/7e458b30a70e1f487da22d271e09676828868250/fda-model/compute/ImpactAreaScenarioSimulation.cs#L851

**Comment by rnugent3** [comment]
more recently we saw that there was not exactly a problem with the input data, the histogram was populated with non-zero data, but estimated iterations remaining producing a double > int.max

**Comment by HenryGeorgist** [comment]
yeah, we need to fix that to return something more like a double = int.max-1 or something...

**Comment by rnugent3** [comment]
ohhhh okay thanks I will do that! I was thinking that the validation was not working because it seemed odd that we'd still hit the exception despite the new validation. I couldn't test it though because the tests pass locally with the lower overlap threshold.

**Comment by rnugent3** [comment]
I think we need the smallest threshold required to compute successfully. I am going to change to 5%. I don't think it is the model's job to make sure that the user has "good" data ... just to make sure that the data is "good enough" for a compute.
