### ISSUE TITLE
twos complement yet again

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#319]
All of the cases where we've run into the twos complement thing in threadsafe histogram have thus far been the result of trying to identify whether a histogram that has only 0s is converged and/or how many iterations remaining. 

In the case, it simply seems that the number of estimated iterations remaining are just really big. 
So the productTerm = 2265644753.2365952 and then we try to convert that to an int and it becomes int.MinValue or whatever. 

I am thinking that the solution to this is to move to Int64. Part of the problem is that we're seeing the need for a lot of iterations to converge, e.g. 2-3 million. 

![image](https://user-images.githubusercontent.com/25163165/178785200-6e655520-753a-4689-80b7-50795d733b1e.png)

**Comment by rnugent3** [comment]
I also wonder if the convergence test assumption that the histogram is normally distribution has an impact. We are seeing everything but normal distributions.

**Comment by HenryGeorgist** [comment]
there isnt a normal assumption for convergence

**Comment by HenryGeorgist** [comment]
i always wanted bincounts to be an int64 array as well as max iterations to be an int64 - but that might just be postpoining a broader issue.

**Comment by rnugent3** [comment]
check if the double productTerm is bigger than integer.max - catch this in validation

**Comment by rnugent3** [comment]
this problem is intermittent. this morning, I could view results. now, I cannot, I hit the exception.

**Comment by rnugent3** [comment]
this problem has been stepped over by not using a parallel compute but we never actually diagnosed the problem. closing the issue as of PR #336
