### ISSUE TITLE
kink in flow-frequency

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#332]
There is a kink in the flow-frequency samples, and I think this has to do with the number of ordinates produced using bootstrap to paired data. I think the number of ordinates needs to be increased to 1000 so that we are not "extrapolating" flows beyond the current max frequency of .9975.

**Comment by HenryGeorgist** [comment]
instead of using 1000 uniform points make a descrete sample at important values... we could approximate it with 250 well placed points in probability space

**Comment by rnugent3** [comment]
do you have a set of points or some math in mind?

**Comment by rnugent3** [comment]
whatever we do here I imagine we'll also want to do in graphical

**Comment by HenryGeorgist** [comment]
id ask beth.
