### ISSUE TITLE
Inconsistent results threadsafe inline histogram

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/fda-model#340]
Test pass or fail somewhat randomly it seems. I've observed it on ThreadsafeHistogramTests.Parallel_Hisogram_Convergence. The value for err. fluctuates every run when you debug, and sometimes fails the test.

**Comment by Brennan1994** [comment]
The value for err is inconsistent always, but it's worse always using dotnet 6. How frustrating. Earlier our tolerance was high enough we never noticed. (or I never noticed)

**Comment by rnugent3** [comment]
This has been happening with 4.8, and this is not the only test. There are other convergence tests based on thread safe histo that also sometimes pass and sometimes fail.

**Comment by Brennan1994** [comment]
fair enough. I'll make a note and overlook it for the move to 6.0 then. Is this something we need to track down ya think?

**Comment by rnugent3** [comment]
My only concern is that results vary by compute. I thought if we had seeded things sufficiently this would not happen.
