### ISSUE TITLE
Precision appropriate for multiplication

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/fda-model#47]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/d45c803ad41e42332fd0cf561e77f3fc7586ade2/fda-model/paireddata/PairedData.cs#L124

Is the fragility curve probability probability or stage probability? this impacts the precision that is appropriate for the buffer argument in the multiply method.

**Comment by Brennan1994** [comment]
We need to get a nice integration test set up to describe the compute. In my old set of test data I made to test pairedData - before I drastically simplified it, I had laid out a test case multiplying Stage Damage and a Fragility Curve. You can see that in the deleted code from This Commit: https://github.com/HydrologicEngineeringCenter/fda-model/commit/801ab06499a3e27c4605e833667e33fab1f2fae0

StageDamage is the subject curve and has Stages for X and Damages for Y. 
The fragility curve is the input curve, which has stages for x, and probabilities for y. 

That buffer is added to bottom, which is an X value of the input fragility curve "g" https://github.com/HydrologicEngineeringCenter/fda-model/blob/d45c803ad41e42332fd0cf561e77f3fc7586ade2/fda-model/paireddata/PairedData.cs#L127
https://github.com/HydrologicEngineeringCenter/fda-model/blob/d45c803ad41e42332fd0cf561e77f3fc7586ade2/fda-model/paireddata/PairedData.cs#L135

I believe the units on that buffer are feet, and in that case .001 is an appropriate value.

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/d45c803ad41e42332fd0cf561e77f3fc7586ade2/fda-model/ead/simulation.cs#L12
Here is the simulation class, it pretty clearly shows the paired data relationships for the various relationships. 

My go-fda code does a pretty good job of showing the relationships too:
https://github.com/HenryGeorgist/go-fda/blob/e2b48f535d948205eed917065980edff037bc99a/expectedannualdamage/expectedannualdamage.go#L25
In the test relationships for levees I did it with stage, failure frequency (consistent with your assertion)
https://github.com/HenryGeorgist/go-fda/blob/e2b48f535d948205eed917065980edff037bc99a/expectedannualdamage/expectedannualdamage_test.go#L164

**Comment by Brennan1994** [comment]
All I really meant is I want something in this project where I can see what X and Y map to. We'll get there. It was more an observation than a complaint. 

The go stuff shows it pretty well too.

**Comment by HenryGeorgist** [comment]
I think the other option is to create a damage frequency curve, and then multiply. Im not sure it matters, it would be neat to test both and see if it makes a difference.

**Comment by Brennan1994** [comment]
If I'm following your suggestion, we'd calculate all the way to damage frequency, the multiply that relationship by a fragility curve? I think we'd have to complicate our workflow a bit to get the frag curve into the right units. we'd need to compose it into a FrequencyOfStage-FailureProbability relationship to get out with reasonable units.

**Comment by rnugent3** [comment]
This is a topic that came up during discussions on the EM 1110-2-1619 update. I'll look for my notes and get back to you guys on this ASAP.

**Comment by rnugent3** [comment]
"FDA develops a table, like a spreadsheet. The first column is the “computation probabilities” which are a maximum of 200 (usually around 150). For each probability, there are corresponding columns of flow (if flow-frequency), exterior stage, interior stage, probability of failure, and damage. The probability of failure is computed by taking the exterior stage and interpolating the probability of failure from the fragility curve. The EAD is computed by the normal trapezoidal method using the average probability of failure to reduce the incremental EAD in each trapezoid." 

I will forward the email this quote came from.

**Comment by Brennan1994** [comment]
If that quote is our guidance, I think we have free reign to make that call then. It doesn't describe how to incorporate that probability of failure back into EAD. it just says to get it from a fragility curve. This doesn't seem like it'll be a tough experiment. Once we have an integration test demonstrating the compute, we can just make a copy of it and do it again with a slightly different approach and see how it differs.

**Comment by HenryGeorgist** [comment]
i dont understand what I am supposed to do with levees. I have a PairedData that represents frequency_floodplainstage (y,x) and a levee that is probability-stage (y,x)? how does this work? do i join on stage or probability? what do i do? I guess i join based on stage and multiply probability by probability to get a new frequency_floodplainstage_withLevee?

**Comment by HenryGeorgist** [comment]
the comments (and variable names) on the multiply method in paireddata have an assumption that the yvals of the input function are damage. we need to modify those names to be more generic if we are going to multiply probability probability instead of damages.
