### ISSUE TITLE
Write Results Test Cases

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/fda-model#65]
add test cases around results to confirm the behavior changes when desired and doesnt change when not desired

**Comment by rnugent3** [comment]
The first to add to testing is CNEP. Then add cases that carry out Will's description above.

**Comment by rnugent3** [comment]
@HenryGeorgist what do you have in mind for testing behavior changes? Are you thinking about different combinations of input relationships?

**Comment by HenryGeorgist** [comment]
@rnugent3 I dont intend to test behavior changes explicitly, but rather, put tests in place to confirm behavior is as intended. That way future changes will validate that the behavior is still as desired. If a change fails a test, we have to ensure that is intended or not. The test is a way to signal that no unintended behavior changes occur with any given commit.

**Comment by rnugent3** [comment]
Would you mind giving me an example? I am not sure what behavior means as it relates to our code.

**Comment by HenryGeorgist** [comment]
Results produce a mean ead.
Results produce a mean aep.
Results produce an estimate of the assurance of AEP
Results produce CNEP
Results produce LTEP (for provided years)
Etc.

The ability to produce these outputs is a "behavior"

**Comment by rnugent3** [comment]
Got it. We have these tests for a few cases. I admit we need more cases. Also, we'll need similar tests for the logic I add over the next two weeks. I am going to close this issue and add more specific issues.
