### ISSUE TITLE
Add label to x and y, name, description, int ID 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#69]
to Uncertain Paired Data

**Comment by rnugent3** [comment]
Uncertain paired data object: Add label to x and y, name, description, int ID 

Impact area should have an int ID

**Comment by rnugent3** [comment]
@HenryGeorgist do you see the labels, name, description, and ID being arguments for a loaded constructor?

**Comment by rnugent3** [comment]
only uncertain paired data is stored

    create complex object "CurveConfiguration" that has the above stuff
    Need to consider what the labels are (e.g. general or distribution specific)

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/fda-model/blob/f52a1dea0219cc44d14af55f71433e859c124237/fda-model/paireddata/UncertainPairedData.cs#L17
i believe this is complete.
