### ISSUE TITLE
Results Refactor

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#86]
We need to refactor results. The primary object is to make sure that we produce the results we've planned and that these results are publicly accessible. 

One thing off the top: the histograms of AEPs and EADs must be public. 

Another: take a look at the way that thresholds are added and results are returned - does the current set up allow these two actions to work together?

**Comment by rnugent3** [comment]
@HenryGeorgist I think we had a discussion about a way to improve what currently exists, but I cannot recall what we said. Do you remember your recommendations?

**Comment by HenryGeorgist** [comment]
@rnugent3 off hand, no.

**Comment by HenryGeorgist** [comment]
one thing that comes to mind in defining the behaviors and reviewing the code for #65 is that IContainResults is an empty interface, which is not an ideal case. Maybe there isnt an interface that can encompass the variety of the results we have.

**Comment by rnugent3** [comment]
Right - we talked about the interface. Thanks. I'll think about a way that we could use the interface.
