### ISSUE TITLE
refactor histogram 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/fda-model#87]
yeah a one bin either centered or starting on the observation

_Originally posted by @HenryGeorgist in https://github.com/HydrologicEngineeringCenter/fda-model/pull/85#discussion_r770911792_

**Comment by rnugent3** [comment]
@HenryGeorgist I think you did the work to close this issue?

**Comment by HenryGeorgist** [comment]
yeah the code in statistics reflects the ability to create a single binned histogram based on a single observation.

**Comment by rnugent3** [comment]
great! I will close this issue. THank you!
