### ISSUE TITLE
update builder pattern to allow for adding thresholds to the simulation

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/fda-model#98]
since everything else is done with the builder pattern we should be consistent.

right now there is a getter for performancemetrics which gives access to the pointer in the simulation class to metric thresholds, which exposes a way to add thresholds.

we should just have a "withThreshold(Threshold threshold)" which could be called multiple times i believe.

**Comment by rnugent3** [comment]
Got it - makes sense. So this is how we would add additional thresholds (additional - in addition to the default)

**Comment by HenryGeorgist** [comment]
addressed in #103
